name: google_ml_kit_remote_model
description: A Flutter Plugin for ML Kit - Manage Custom Remote Model.
version: 0.0.1
homepage: https://github.com/bharat-biradar/Google-Ml-Kit-plugin
publish_to: none # TODO: remove once split is ready

environment:
  sdk: ">=2.16.0 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  google_ml_kit_commons:
    path: ../google_ml_kit_commons

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.google_ml_kit_remote_model
        pluginClass: GoogleMlKitRemoteModelPlugin
      ios:
        pluginClass: GoogleMlKitRemoteModelPlugin
