# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Static code analysis

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  lint:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-java@v1
      with:
        java-version: '12.x'
    - uses: subosito/flutter-action@v1.5.3

    - name: Install Dependencies for google_ml_kit
      working-directory: ./packages/google_ml_kit
      run: flutter pub get
    - name: Install Dependencies for google_ml_kit_barcode_scanner
      working-directory: ./packages/google_ml_kit_barcode_scanner
      run: flutter pub get
    - name: Install Dependencies for google_ml_kit_commons
      working-directory: ./packages/google_ml_kit_commons
      run: flutter pub get
    - name: Install Dependencies for google_ml_kit_face_detection
      working-directory: ./packages/google_ml_kit_face_detection
      run: flutter pub get
    - name: Install Dependencies for google_ml_kit_pose_detection
      working-directory: ./packages/google_ml_kit_pose_detection
      run: flutter pub get

    # Check for any formatting issues in the code.
    - run: flutter format --set-exit-if-changed .

    # Statically analyze the Dart code for any errors.
    - run: flutter analyze .
